# SAM CLI configuration file

version = 0.1

[default]
[default.global.parameters]
stack_name = "notification-service"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
region = "us-east-1"
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Development stage
[dev]
[dev.deploy.parameters]
stack_name = "notification-service-dev"
s3_prefix = "notification-service-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev EmailProvider=MOCK SmsProvider=MOCK"

# Staging stage
[staging]
[staging.deploy.parameters]
stack_name = "notification-service-staging"
s3_prefix = "notification-service-staging"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=staging EmailProvider=AWS_SES SmsProvider=AWS_SNS"

# Production stage
[prod]
[prod.deploy.parameters]
stack_name = "notification-service-prod"
s3_prefix = "notification-service-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=prod EmailProvider=AWS_SES SmsProvider=AWS_SNS PushProvider=AWS_SNS"
